### ISSUE TITLE
Add Names to Project Partners

### ISSUE THREAD

**Issue by metaweidner** [Bridge2Hyku/Bridge2Hyku.github.io#2]
@crocken Please add the names of participants and their project roles (if appilcable) to the Project Partners page: https://github.com/Bridge2Hyku/Bridge2Hyku.github.io/blob/master/pages/partners.md

**Comment by crocken** [comment]
@metaweidner added them below the institutions. let me know if this works or you would prefer individual participants in its own area as "project team", then change the current "project team" subtitle to "partner institutions"

**Comment by metaweidner** [comment]
@crocken Feel free to close this after removing the Project Directors label and the break between UH personnel, and adding Principal Investigator as a role.

**Comment by crocken** [comment]
done :)
