### ISSUE TITLE
Update Project Partner Categories

### ISSUE THREAD

**Issue by metaweidner** [Bridge2Hyku/Bridge2Hyku.github.io#3]
@crocken Please make two changes to the Project Partners page: https://github.com/Bridge2Hyku/Bridge2Hyku.github.io/blob/master/pages/partners.md

1. Change the 'Project Advisors' label to 'Technical Advisors'
2. Create a new 'Community Stakeholders' label and move DuraSpace and DPLA to that category

**Comment by crocken** [comment]
both done.  Would you prefer testing and closing these or can I close them if they're done?
