### ISSUE TITLE
Add Survey Questions Text

### ISSUE THREAD

**Issue by metaweidner** [Bridge2Hyku/Bridge2Hyku.github.io#5]
@crocken Please add the text of the collections survey to the Survey page: https://github.com/Bridge2Hyku/Bridge2Hyku.github.io/blob/master/pages/survey.md

**Comment by crocken** [comment]
https://github.com/Bridge2Hyku/Bridge2Hyku.github.io/commit/0fedbc2abfe76b2d9767f2e913d9b010194c8b35
