### ISSUE TITLE
Add Logo to B2H Github Org

### ISSUE THREAD

**Issue by metaweidner** [Bridge2Hyku/Bridge2Hyku.github.io#6]
upload a logo for the B2H Github org

**Comment by crocken** [comment]
@metaweidner andy- "member"s of an organization dont have the access to edit/change logos.

**Comment by metaweidner** [comment]
@crocken Let @seanlw know when you have a logo and he can get this done.

**Comment by crocken** [comment]
![github-logo](https://user-images.githubusercontent.com/35815515/38892336-94ddbc44-424c-11e8-98a5-05b5b8df28ec.png)

**Comment by crocken** [comment]
@seanlw this 500x500 png should suffice. :)
