### ISSUE TITLE
Adjust Heading Navigation Links for Banner

### ISSUE THREAD

**Issue by metaweidner** [Bridge2Hyku/Bridge2Hyku.github.io#7]
When heading navigation links are clicked, the banner obscures the heading.

**Comment by crocken** [comment]
@seanlw sean- this might be something you could fix in 2 minutes instead of me taking much longer to figure it out....  https://bridge2hyku.github.io/hyku/#features  if you click on "hyku features" notice that the header hides the first chunk of the content.

**Comment by seanlw** [comment]
Fixed in 0ff89215455f626a3781646db9324f6f54169e56
